# hx-exec aliases for Helix

[alias.angular-lsp]
command = "ngserver"
args = [
  "--stdio",
  "--tsProbeLocations", "${NODE_MODULES}/typescript/lib",
  "--ngProbeLocations", "${NODE_MODULES}/@angular/language-server/bin",
]
env.NODE_MODULES = { cmd = "npm root -g" }
