# hx-exec aliases for Helix
# Alias for Angular language server: expand npm -g root into NODE_MODULES
[[alias.angular-lsp]]
command = "ngserver"
args = [
  "--stdio",
  "--tsProbeLocations", "${NODE_MODULES}",
  "--ngProbeLocations", "${NODE_MODULES}",
]
[alias.angular-lsp.env.NODE_MODULES]
cmd = "npm -g root"
